Add ipad platform, checkMobile for vk
ktsstudio/mediaproject-vk pull request #1
Opened 2021-11-02 09:15 UTC by AliceSitedge

2021-11-11 17:48 UTC, n-merkulova approved these changes

2021-11-11 18:55 UTC, wayvy commented on src/vibrate.ts
>  } from './types/vabrations';
v**a**brations

2021-11-12 10:26 UTC, merged

2021-11-12 12:28 UTC, natalya-z requested changes

2021-11-12 12:28 UTC, natalya-z commented on src/allowMessagesFromGroup.ts
>  export default async (group_id = Number(window.group_id)): Promise<boolean> => {
добавить метод запрета уведомлений: https://vk.com/dev/vkbridge/vkwebappdenynotifications
референс: 
https://gitlab.team.ktsstudio.ru/-/ide/project/mailru-nonstandart/whiskas-front/tree/master/-/src/utils/notifications/notifications.ts/
https://gitlab.team.ktsstudio.ru/-/ide/project/mailru-nonstandart/whiskas-front/tree/master/-/src/utils/notifications/useNotificationsSubscribe.ts/

2021-11-12 12:28 UTC, natalya-z commented on src/getAuthToken.ts
> + * Получает access token с переданными параметрами access scope.
access  => параметрами доступа

2021-11-12 12:28 UTC, natalya-z commented on src/setViewSettings.ts
> + * По умолчанию устанавливает темный цвет содержимого статус-бара (status_bar_style: 'dark') и белый фон (action_bar_color: 'white'),
разделить понятия status_bar_style: dark, light и то, что action_bar_color может быть разным цветом