v3.0.0: Удаление записи полей с параметрами приложения в window
ktsstudio/mediaproject-vk pull request #18
Opened 2023-12-22 12:17 UTC by kurakinasv

**Задача [SPECIAL-11631](https://youtrack.kts.studio/issue/SPECIAL-11631/mediaproject-vk-Ubrat-zapis-v-window-polej-s-parametrami-prilozheniya-dlya-miniappa-VK)**:

- отрефакторить утилиту `checkVkPlatform`, чтобы она не обращалась к window
- убрать лишние поля из типа `WindowType`

**Что было сделано:**

- Опираясь на [пример в другом проекте](https://git.kts.tech/mailru-nonstandart/sber-chan-comics-front/-/blob/main/src/store/globals/appParams/AppParamsStore/AppParamsStore.ts), отрефакторены утилиты `checkVkPlatform`, `setVkViewSettings` и `initializeVkApp` – удалены обращения к window
- Из утилиты `getNewVkAccessToken` убрано значение по умолчанию. В соответствии с этим немного подкорректированы другие методы, которые так или иначе связаны с запросом за токеном
- Из `WindowType` убраны поля, которые не должны храниться в window: параметры запуска и параметры определения платформы
- Подняла версию до 3.0.0, так как по крайней мере в функции `setVkViewSettings` было изменено количество аргументов

**Как тестировалось:**

- **! Спойлер: не получилось протестить из-за проблемы, описанной чуть ниже**
- Закомменчена часть с авторизацией в проекте
- mediaproject-vk и -stores были связаны с -utils с помощью `yarn link` ([версия stores](https://github.com/ktsstudio/mediaproject-stores/pull/11), [версия utils](https://github.com/ktsstudio/mediaproject-utils/pull/16))
- Проект был связан с vk, stores и utils
- Заменено использование локальных функций `checkVkPlatform`, `setVkViewSettings` и типов `DeviceInfo` и `VkPlatformType` на одноименные из либы
- Заменены другие утилиты на одноименные из mediaproject-utils и -stores (описано в пр'ах по ссылкам выше)

**Проблема:**
- После запуска проекта появлялась ошибка, предположительно связанная с существованием двух разных зависимостей реакта в проекте и в mediaproject-vk ([скрин](https://drive.google.com/file/d/1_uxojwe27cZaibKHr-EV6B4fl-wdGARW/view?usp=sharing))
- Уравнивание версий react, react-dom и их типов в проекте и либе не спасло.
- [Пример дебага](https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) из доки реакта выводит true, с зависимостями вроде тоже все в порядке

2023-12-25 11:15 UTC, AliceSitedge requested changes

2023-12-25 11:15 UTC, AliceSitedge commented on src/callVkApi.ts
> +  getAccessTokenParams,
С текущими изменениями у функции меняется поведение. Раньше, если в getAccessTokenParams ничего не передано, запрос за токеном все равно происходил, потому что appId функция могла достать самостоятельно. А сейчас получается запроса за токеном не будет и запрос к апишке будет неуспешный в случае отсутствия токена

Как будто лучше getAccessTokenParams сделать обязательным аргументом, чтобы appId всегда передавался

2023-12-29 08:20 UTC, AliceSitedge approved these changes

2024-01-30 12:18 UTC, dewolixgit commented
Переназначил целевую ветку с master на release-3.0.0 для подготовки PR по релизу 3.0.0

2024-01-30 12:20 UTC, merged