Покрытие тестами
ktsstudio/mediaproject-vk pull request #20
Opened 2024-01-16 09:20 UTC by dewolixgit

- Было настроено окружение для тестирования
  - Не настроены алиасы для джеста, так как не увидел надобности их делать в условиях примитивной структуры папок

2024-01-22 11:16 UTC, natalya-z requested changes
1) Не добавлены обновления в change.log
2) Не добавлено в read.me описание как запустить тесты
3) Лучше бы вынести списочек тестов отдельно, чтобы понимать списочек вообще

2024-01-23 06:55 UTC, dewolixgit commented on src/setVkViewSettings.ts
> -      window.platform &&
Это чтобы заранее заложиться на изменения в [мр по удалению записи в window параметров приложения](https://github.com/ktsstudio/mediaproject-vk/pull/18/files#diff-d02206b44a03ca5792dedc957b8f705f95fb7b500ee430fad256581c7d0623ae)

2024-01-23 08:17 UTC, dewolixgit commented on src/__tests__/isVkError.test.ts
> +        'с произвольным request_id, но с отсутствующим error_data',
Скорее, просто попытка обмана проверки имитацией настоящего объекта с ошибкой. Дополнил название теста

2024-01-26 15:23 UTC, natalya-z commented on CHANGELOG.md
> +# v3.0.0
а поднять версию в package.json?

2024-01-29 14:38 UTC, natalya-z approved these changes

2024-01-30 11:09 UTC, qpounodb requested changes

2024-01-31 09:35 UTC, dewolixgit commented on src/__tests__/callVkApi.test.ts
> +jest.mock('@vkontakte/vk-bridge');
Интересно, спасибо

2024-01-31 09:50 UTC, dewolixgit commented on src/__tests__/checkVkUserDenied.test.ts
> +        error_reason: errorReason,
Это, скорее, для теста "Объект ошибки, соответствующий типу ошибки api_error, но с error_reason <какой-то error_reason> и кодом ошибки 4". Притом ошибка отказа юзера имеет тип client_error. То есть здесь проводится попытка обмана проверки, подсовыванием функции объекта ошибки с корректными кодом ошибки, причиной ошибки, но с некорректным типом ошибки

2024-01-31 09:53 UTC, dewolixgit commented on src/checkVkAvatarIsDefault.ts
> +  !!photo && photo === `https://vk.com/images/camera_${size}.png`;
Да, действительно, упустил

2024-01-31 11:03 UTC, qpounodb commented on src/__tests__/checkVkUserDenied.test.ts
> +        error_reason: errorReason,
Понял, спасибо

2024-01-31 11:04 UTC, qpounodb approved these changes

2024-02-06 14:29 UTC, merged