2.0.0
ktsstudio/mediaproject-vk pull request #8
Opened 2023-01-19 19:15 UTC by n-merkulova

2023-01-20 17:29 UTC, AliceSitedge requested changes

2023-01-20 17:29 UTC, AliceSitedge commented on src/callApi.ts
> +  renewTokenIfExpired = false,
Мне кажется обновление токена, если он протух, нужно сделать по умолчанию, потому что почти во всех случаях это не помешает, и не хочется каждый раз прокидывать `renewTokenIfExpired: true`. И тогда нужно getAccessTokenParams сделать обязательным, будет меньше ошибок, если нужно будет явно указать, что скоупы никакие не нужны

И еще я бы в доке написала, как пользоваться методом, а то может быть непонятно, что за `renewTokenIfNoneProvided` и `renewTokenIfExpired` и в каких случаях они нужны

2023-01-20 17:29 UTC, AliceSitedge commented on src/checkPlatform.ts
> + *  и добавляет класс 'mobile' или 'desktop' на document.body в зависимости от результата проверки.
```suggestion
 * и добавляет класс 'mobile' или 'desktop' на document.body в зависимости от результата проверки.
```

2023-01-20 17:29 UTC, AliceSitedge commented on src/sharePost.ts
> +}: SharePostParamsType): Promise<SharePostResponseType | undefined> => {
Или ошибка?

2023-01-20 17:29 UTC, AliceSitedge commented on src/types/shareStory.ts
> +export type ShareStoryParamsType = {
А нет вкшного типа для этого? А то мб нужно будет что-то еще прокинуть

2023-01-20 17:29 UTC, AliceSitedge commented on CHANGELOG.md
> +- [*] initializeApp
А если старую версию установить, там же будет `initializeVkApp`, мб в описании старых версий так и оставить?

2023-01-23 16:56 UTC, natalya-z requested changes
Общее примечание: хорошо бы добавить описание параметров методов и ссылки на методы вк бридж, используемые внутри. Так бы разработчик быстрее разобрался в логике, а-то тратится время на поиск метода в доке вк

2023-01-23 16:56 UTC, natalya-z commented on src/sharePost.ts
> +const sharePost = async ({
для шеринга в сниппет будет эта функция? для этого в параметр extra надо будет прокинуть нужные поля?

2023-01-23 16:56 UTC, natalya-z commented on src/sharePost.ts
> -    console.log(e);
для дева не помешали бы логи, часто без них тяжело делать дебаг

2023-01-23 16:56 UTC, natalya-z commented on src/types/sharePost.ts
> +  extra?: Partial<WallPostRequestOptions>;
в типе WallPostRequestOptions нет типизации параметро для шера в сниппет, может стоит их добавить к типу extra?

2023-01-23 16:56 UTC, natalya-z commented on src/types/shareStory.ts
> +};
тут не хватает extra (как в sharePost) или полного описания дополнительных параметров шеринга в историю
https://dev.vk.com/bridge/VKWebAppShowStoryBox
![image](https://user-images.githubusercontent.com/63305213/214091113-16d37f7a-7a21-4894-8f55-df7718395e96.png)

2023-01-23 16:56 UTC, natalya-z commented on src/callApi.ts
> +const callApi = async ({
не очень нравится название, так как разработчик при первом взгляде не сообразит, что тут вызывается апи вк, а только после того, как посмотрит, откуда этот метод импортируется.
так же сложно будет не запутаться в приложениях, где и вк, и ок.
метод с таким названием есть внутри метода api для вызова методов нашего бэка - то же можно создать путаницу

2023-01-24 17:52 UTC, n-merkulova commented on src/setViewSettings.ts
> +  'mobile_android',
ну по идее нет, так как поддержка этой фичи довольно ограничена. предполагаю, что external платформы это, например, сторонние клиенты для вк (типа как был kate mobile), а у них непонятно, есть ли такой функционал вообще

2023-01-24 17:53 UTC, n-merkulova commented on src/setViewSettings.ts
> +    return error;
вообще подразумевалось, что проверку на поле error_type внутри возвращаемого объекта

2023-01-25 19:07 UTC, n-merkulova commented on src/types/sharePost.ts
> +  extra?: Partial<WallPostRequestOptions>;
их нету в открытой документации вк, в коде vk bridge их тоже нет. не знаю, насколько легально их добавлять... но добавлю)))

2023-01-27 15:19 UTC, n-merkulova commented on src/sharePost.ts
> -    console.log(e);
думаю, не нужно, потому что метод возвращает прям весь объект ошибки, который приходит от вк

2023-01-30 15:42 UTC, natalya-z approved these changes

2023-01-31 08:34 UTC, AliceSitedge approved these changes

2023-01-31 08:34 UTC, AliceSitedge commented on src/getVkAccessToken.ts
> +const checkVkScopesAreEqual = (
Тут не проверка на equal получается, а проверка на то, что одно множество входит в другое, и важно при использовании понимать, какое именно вхождение проверятся, так что я бы переименовала

2023-01-31 13:33 UTC, merged